### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by hellc** [k2kobayashi/crank#19]
@k2kobayashi Thank you for your work!

Could you please make it more Windows friendly like you did it with https://github.com/k2kobayashi/sprocket?
The file path rules in crank on windows is a disaster...I think you have already know about it :D

**Comment by k2kobayashi** [comment]
Hi, I don't know what is the exact reason you cannot run on Windows.
crank is implemented for Linux environment as well as sprocket. I think wsl2 may help you to run on windows.
