### ISSUE TITLE
Dataset question

### ISSUE THREAD

**Issue by pavelxx1** [k2kobayashi/crank#25]
Hi, first thx for this great repo!)
I have question
 -  For best result I need dataset with small duration length ie 10sec per wav or better when length above 1-2min for one speaker
Thx!

**Comment by k2kobayashi** [comment]
If the feature vectors are extracted correctly, that's no problem. But I assumed every audio length is  around 5s.

**Comment by pavelxx1** [comment]
Thx, 
1) How many wav- files(dataset) need for good training result?
2) If I want convert speakerA to speakerB can I use small dataset of speakerA, ie 5-10 wav-files?
Thx

**Comment by k2kobayashi** [comment]
1. vcc2020v1 and vcc2018v1 use about 1k utterances for training and it produces acceptable quality.
2. I didn't try such condition. I predict 10~30 utterances / speaker is minimum # of training utterances for 2 speaker modeling.
