### ISSUE TITLE
Poor conversion quality. What am I doing wrong?

### ISSUE THREAD

**Issue by pavelxx1** [k2kobayashi/crank#27]
Hi!
My result test conversation from speakerA -> speakerB are poor..
Details:
 - speakerA dataset have 10 wav with length 5 sec for each file
 - speakerB have ~500 wav with same length (5 sec per file)
 - f0 & pow was tuned from this [FAQ](https://www.slideshare.net/NU_I_TODALAB/hands-on-voice-conversion)
You can see my exp from [GDrive](https://drive.google.com/drive/folders/19x0wh1IihkB4sAVtWiRfpO0MozqtnHDm?usp=sharing)

What am I doing wrong? Thx!

**Comment by k2kobayashi** [comment]
How poor do you feel? sound quality, speaker similarity, robotics, or unintelligible?

**Comment by pavelxx1** [comment]
the main think -  bad speaker similarity.
 i.e speakerA is not similarly to speakerB
