### ISSUE TITLE
Output audio is shorter than input audio

### ISSUE THREAD

**Issue by DareenHarthi** [k2kobayashi/crank#31]
Hello, 

Each input file in my dateset is 6 seconds long but the output samples are 3 seconds long, what should I change to make the output time same as the input?

Also the results are bad are there any settings should I change?

**Comment by k2kobayashi** [comment]
Which output samples do you have the problem development set or evaluation set?
And please show me your input and output samples.

**Comment by DareenHarthi** [comment]
I have a custom dataset, I didn't use VCC dataset.
samples:
[samples.zip](https://github.com/k2kobayashi/crank/files/5524850/samples.zip)

I changed the spkr.yml file as you described in the README, I have two speakers only both are males, spkr.yml file:
`aziz:
  minf0: 90
  maxf0: 250
  npow: -20
kalbani:
  minf0: 70
  maxf0: 240
  npow: -20`

**Comment by k2kobayashi** [comment]
The input waveform has two channels. crank only supports single channel audio file.

**Comment by DareenHarthi** [comment]
How to convert the input to single channel to work with crank?

**Comment by k2kobayashi** [comment]
Using sox is easy way.
```
sox input.wav -c 1 output.wav remix 1
```

**Comment by talka1** [comment]
the development set are 3 seconds long, i think thats how it supposed to be. the evaluation waveform will be generated after stage 7 i guess?
