### ISSUE TITLE
Recipe issues

### ISSUE THREAD

**Issue by unilight** [k2kobayashi/crank#37]
In this thread, I will post some problems I find when checking the recipe code.

In https://github.com/k2kobayashi/crank/blob/master/crank/bin/generate_scp.py#L81, if the scp directory already exists, then the generation process won't be executed. However, in https://github.com/k2kobayashi/crank/blob/master/egs/vaevc/template/run.sh#L49, the scp directory is always created first.

I guess the design is to avoid generating the scps again if they already exist? Personally I think it is okay to run the process every time. Shall we skip such check ...?

**Comment by k2kobayashi** [comment]
Thanks. You are right. Maybe I add the check to avoid unexpected overwrite of scp files. I'll modify it.
