### ISSUE TITLE
Why my generated waveform on VCC2020 is slower than original one

### ISSUE THREAD

**Issue by mortyzhou77** [k2kobayashi/crank#51]
![image](https://user-images.githubusercontent.com/54799259/129953004-22fd83ba-2183-4ae2-b023-b248ddd821fe.png)
This is generated one, the speech of speech is twice slower than orignal one... and my pwg vocoder just train to 200000.ckpt

this is the duration of same waveform for original and your sample ：
![image](https://user-images.githubusercontent.com/54799259/129953422-f2401632-d466-48e1-af70-a9489b9a1841.png)

And I used the default configuration and setup...Could you help me to fix this kind of problem？ Does it will influence the MCD and MOSNET outcome？

**Comment by unilight** [comment]
Hi @zhouyh-jlu , did you train your own PWG? You may check the hop size and upsampling stride numbers. And yes, it will affect the MCD and MOSNet results.

**Comment by mortyzhou77** [comment]
> Hi @zhouyh-jlu , did you train your own PWG? You may check the hop size and upsampling stride numbers. And yes, it will affect the MCD and MOSNet results.

Yes, I found I used PWG from espnet's vcc2020 and some issues for hop size. Thank you for your help.

**Comment by talka1** [comment]
so what did you exactly do to fix the problem with the slowed down generated Eval Wavs after step 6?
