### ISSUE TITLE
Waveform load/write module

### ISSUE THREAD

**Issue by unilight** [k2kobayashi/crank#9]
I found that in PR #3 you changed from using `wavfile` to using `soundfile`. If we use `wavfile` to load waveform, the values will be in `[-32768, 32767]`, and for `soundfile` the range is `[-1, 1]`. But, for WORLD features, since we still use the `Synthesizer` class from sprocket, according to https://github.com/k2kobayashi/sprocket/blob/master/example/src/convert.py#L160-L161, I think `Synthesizer` will synthesize waveform ranging from `[-32768, 32767]`.
I wonder if there was a specific reason for PR #3 ?

**Comment by k2kobayashi** [comment]
The outcome of ```Synthesizer``` depends on the mel-cepstrum (especially 0th order). When I use ```soundfile```, the outputs of ```Synthesizer``` subside ```[-1, 1]```.
The reason why I change waveform read API is 0-th order modeling. I heard it tends to ease the buzzy sound of converted speech by using ```[-1, 1]``` range.

**Comment by unilight** [comment]
Okay I understand now. Thank you!
